---
title: "Base R and Dplyr functions"
author: "Lyn Howard"
output: webexercises::webexercises_default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(webexercises)
```

<iframe width="560" height="315" src="https://www.youtube.com/embed/JfWm-ECqXts?si=RdseoRHMFwtoO9ON" data-external="1" allowfullscreen>

</iframe>

## Test your understanding

```{r, echo = FALSE, results='asis'}
# Uncomment to change widget colours:
#style_widgets(incorrect = "goldenrod", correct = "purple")
```

What is the total attendance across the 5 rows with the lowest attendances? `r fitb(15)`

`r hide("See a hint")`

Use **?slice** to look at the help file to find the function you need to get a small dataframe of the 5 rows with the lowest attendance. You can then use **sum()** to get the total of the attendances column.

`r unhide()`

```{r, echo = TRUE, eval = FALSE, webex.hide = "Click here to see an explanation"}
q1_df<- slice_min(data, n=5, order_by = breaches)

sum(q1_df$attendances) # This will give the answer = 15
```
