---
title: "Intermediate R course, part 5"
output: webexercises::webexercises_default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(webexercises)

```

<iframe width="560" height="315" src="https://www.youtube.com/embed/............" data-external="1" allowfullscreen>

</iframe>


## Transcript and code

```{r eval=TRUE, echo=TRUE}
library(dplyr)

data <- NHSRdatasets::ae_attendances

df_one <- data |>
  select (period,
          org_code,
          type,
          attendances) |>
  head()

df_two <- data |>
  select (where(is.numeric)) |>
  head()
```

```{r eval = TRUE  , echo=FALSE}
df_one |> gt::gt(caption = "df_one")
df_two |> gt::gt(caption = "df_two")
```
```{r eval=TRUE, echo=TRUE}
df_new <- cbind(df_one,
                df_two)
```

```{r eval =TRUE, echo=FALSE}
names(df_new) <- c("period", "org_code", "type", "attendances", "attendances.1", 
"breaches", "admissions")
df_new |> gt::gt(caption = "df_new")  
```


## Test your understanding

```{r, echo = FALSE, results='asis'}
# Uncomment to change widget colours:
#style_widgets(incorrect = "goldenrod", correct = "purple")
```

QUESTION?

```{r}
opts_p <- c("a.        ", 
            "b.        ", 
            answer = "c.     ",
            "d.            "
            )
```

`r longmcq(opts_p)`

`r hide("See a hint")`

HINT GOES HERE


`r unhide()`

```{r, echo = TRUE, eval = FALSE, webex.hide = "Click here to see an explanation"}
EXPLANATION GOES HERE
```
